[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "caution custom crack dentist clap neutral wave salute echo audit win expect scorpion genuine order wave foil echo ride wool airport wave average arrow"
